### ISSUE TITLE
C24c: Duplicate search: other recommendations

### ISSUE THREAD

**Issue by infotel4iarc** [IARC-CSU/CanReg5#102]
• The method DatabaseRecord#getVariable is called very often and it uses toLowerCaseStandardized, which consumes cpu each time.
• The method releaseResultSet is called outside of a “finally” block, which means that the release could not be done if an exception happens.

**Comment by fbinfotel** [comment]
I started working on the issue on 31/08/2021 . The code can be found on this repo : https://github.com/infotel4iarc/CanReg5/tree/feature/C24c

I added a finally block to all method containing a releaseResultSet function in order to be able to release the resultSet if an exception is thrown. 

The branch need to be reviewed

**Comment by fbinfotel** [comment]
I started working on the issue on 31/08/2021 . The code can be found on this repo : https://github.com/infotel4iarc/CanReg5/tree/feature/C24c

I added a finally block to all method containing a releaseResultSet function in order to be able to release the resultSet if an exception is thrown. 

The branch needs to be reviewed

**Comment by fbinfotel** [comment]
Before the optimization, The method DatabaseRecord#getVariable was called very often and it used toLowerCaseStandardized, which consumes CPU each time.
After, the optimization (C24a) this method is used when the data are retrieved from the database. So the CPU consumption is much lower, that why there was no need to modify the getVariable method.
On the other Hand, the modifications on the releaseResultSet were done to be able to release the resultSet even if an exception is thrown. 

The review is done, so the ticket is finished.
